In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/Students Performance Dataset.csv")

In [4]:
df

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,student0@university.com,Female,22,Mathematics,97.36,40.61,59.61,...,62.84,59.8865,F,10.3,Yes,No,Master's,Medium,1,5.9
1,S1001,Maria,Brown,student1@university.com,Male,18,Business,97.71,57.27,74.00,...,98.23,81.9170,B,27.1,No,No,High School,Low,4,4.3
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Engineering,99.52,41.84,63.85,...,91.22,67.7170,D,12.4,Yes,No,High School,Low,9,6.1
3,S1003,Omar,Williams,student3@university.com,Female,24,Engineering,90.38,45.65,44.44,...,55.48,51.6535,F,25.5,No,Yes,High School,Low,8,4.9
4,S1004,John,Smith,student4@university.com,Female,23,CS,59.41,53.13,61.77,...,87.43,71.4030,C,13.3,Yes,No,Master's,Medium,6,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S5995,Ahmed,Jones,student4995@university.com,Male,19,CS,96.09,45.86,45.63,...,51.66,53.5470,F,7.8,No,No,Master's,Medium,10,4.5
4996,S5996,Emma,Brown,student4996@university.com,Male,19,Mathematics,96.30,78.67,47.42,...,52.33,59.0240,F,24.2,No,Yes,NaN,Medium,4,7.2
4997,S5997,John,Brown,student4997@university.com,Female,24,CS,89.94,50.84,65.83,...,97.89,74.7560,C,7.6,No,Yes,NaN,High,5,6.6
4998,S5998,Sara,Davis,student4998@university.com,Male,23,Engineering,99.09,55.44,57.45,...,84.74,68.6585,D,14.5,Yes,No,PhD,Medium,10,5.9
4999,S5999,Maria,Brown,student4999@university.com,Female,21,Mathematics,90.33,93.29,88.42,...,66.23,78.7485,C,29.9,Yes,Yes,PhD,High,2,5.3

In [5]:
df.shape

(5000, 23)

In [6]:
df.columns

Index(['Student_ID', 'First_Name', 'Last_Name', 'Email', 'Gender', 'Age',
       'Department', 'Attendance (%)', 'Midterm_Score', 'Final_Score',
       'Assignments_Avg', 'Quizzes_Avg', 'Participation_Score',
       'Projects_Score', 'Total_Score', 'Grade', 'Study_Hours_per_Week',
       'Extracurricular_Activities', 'Internet_Access_at_Home',
       'Parent_Education_Level', 'Family_Income_Level', 'Stress_Level (1-10)',
       'Sleep_Hours_per_Night'],
      dtype='str')

In [7]:
df.describe(include="all")

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
count,5000,5000,5000,5000,5000,5000.000000,5000,5000.000000,5000.000000,5000.000000,...,5000.00000,5000.000000,5000,5000.000000,5000,5000,3975,5000,5000.000000,5000.000000
unique,5000,8,6,5000,2,NaN,4,NaN,NaN,NaN,...,NaN,NaN,5,NaN,2,2,4,3,NaN,NaN
top,S1000,Maria,Johnson,student0@university.com,Male,NaN,Engineering,NaN,NaN,NaN,...,NaN,NaN,C,NaN,Yes,Yes,Bachelor's,Low,NaN,NaN
freq,1,657,868,1,2551,NaN,1274,NaN,NaN,NaN,...,NaN,NaN,2307,NaN,2512,2520,1020,1687,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,21.048400,NaN,75.356076,70.701924,69.546552,...,74.78305,71.652097,NaN,17.521140,NaN,NaN,NaN,NaN,5.507200,6.514420
std,NaN,NaN,NaN,NaN,NaN,1.989786,NaN,14.392716,17.436325,17.108996,...,14.54243,7.230097,NaN,7.193035,NaN,NaN,NaN,NaN,2.886662,1.446155
min,NaN,NaN,NaN,NaN,NaN,18.000000,NaN,50.010000,40.000000,40.010000,...,50.00000,50.602000,NaN,5.000000,NaN,NaN,NaN,NaN,1.000000,4.000000
25%,NaN,NaN,NaN,NaN,NaN,19.000000,NaN,62.945000,55.707500,54.697500,...,61.97000,66.533875,NaN,11.500000,NaN,NaN,NaN,NaN,3.000000,5.300000
50%,NaN,NaN,NaN,NaN,NaN,21.000000,NaN,75.670000,70.860000,69.485000,...,74.54000,71.696250,NaN,17.400000,NaN,NaN,NaN,NaN,6.000000,6.500000
75%,NaN,NaN,NaN,NaN,NaN,23.000000,NaN,87.862500,85.760000,83.922500,...,87.63000,76.711625,NaN,23.700000,NaN,NaN,NaN,NaN,8.000000,7.800000
max,NaN,NaN,NaN,NaN,NaN,24.000000,NaN,100.000000,99.990000,99.980000,...,100.00000,95.091500,NaN,30.000000,NaN,NaN,NaN,NaN,10.000000,9.000000

In [8]:
df.isnull().sum()

Student_ID                       0
First_Name                       0
Last_Name                        0
Email                            0
Gender                           0
Age                              0
Department                       0
Attendance (%)                   0
Midterm_Score                    0
Final_Score                      0
Assignments_Avg                  0
Quizzes_Avg                      0
Participation_Score              0
Projects_Score                   0
Total_Score                      0
Grade                            0
Study_Hours_per_Week             0
Extracurricular_Activities       0
Internet_Access_at_Home          0
Parent_Education_Level        1025
Family_Income_Level              0
Stress_Level (1-10)              0
Sleep_Hours_per_Night            0
dtype: int64

In [9]:
df["Student_ID"].duplicated().sum()

np.int64(0)

In [10]:
df["Department"].value_counts()

Department
Engineering    1274
Business       1264
CS             1239
Mathematics    1223
Name: count, dtype: int64

In [11]:
df["Grade"].value_counts()

Grade
C    2307
D    1760
B     638
F     279
A      16
Name: count, dtype: int64

In [12]:
df["Gender"].value_counts()

Gender
Male      2551
Female    2449
Name: count, dtype: int64

In [13]:
categorical_columns = [
    "Extracurricular_Activities",
    "Internet_Access_at_Home",
    "Parent_Education_Level",
    "Family_Income_Level"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- Extracurricular_Activities ---
Extracurricular_Activities
Yes    2512
No     2488
Name: count, dtype: int64

--- Internet_Access_at_Home ---
Internet_Access_at_Home
Yes    2520
No     2480
Name: count, dtype: int64

--- Parent_Education_Level ---
Parent_Education_Level
NaN            1025
Bachelor's     1020
PhD            1012
Master's       1000
High School     943
Name: count, dtype: int64

--- Family_Income_Level ---
Family_Income_Level
Low       1687
Medium    1674
High      1639
Name: count, dtype: int64

In [14]:
score_columns = [
    "Midterm_Score",
    "Final_Score",
    "Assignments_Avg",
    "Quizzes_Avg",
    "Participation_Score",
    "Projects_Score",
    "Total_Score"
]

df[score_columns].agg(["min", "max"])

,Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score
min,40.00,40.01,50.00,50.00,0.0,50.0,50.6020
max,99.99,99.98,99.99,99.99,100.0,100.0,95.0915

In [ ]:
df["Student_ID"].isnull().sum()

np.int64(0)

In [16]:
df["Student_ID"].duplicated().sum()

np.int64(0)

In [18]:
((df["Attendance (%)"] < 0) | (df["Attendance (%)"] > 100)).sum()

np.int64(0)

In [19]:
score_columns = [
    "Midterm_Score",
    "Final_Score",
    "Assignments_Avg",
    "Quizzes_Avg",
    "Participation_Score",
    "Projects_Score",
    "Total_Score"
]

((df[score_columns] < 0) | (df[score_columns] > 100)).sum()

Midterm_Score          0
Final_Score            0
Assignments_Avg        0
Quizzes_Avg            0
Participation_Score    0
Projects_Score         0
Total_Score            0
dtype: int64

In [20]:
((df["Age"] < 18) | (df["Age"] > 25)).sum()

np.int64(0)

In [21]:
df["Department"].isin(
    ["Engineering", "Business", "CS", "Mathematics"]
).all()

np.True_

In [22]:
categorical_columns = [
    "Gender",
    "Extracurricular_Activities",
    "Internet_Access_at_Home",
    "Family_Income_Level"
]

for column in categorical_columns:
    print(column, ":", df[column].unique())

Gender : <StringArray>
['Female', 'Male']
Length: 2, dtype: str
Extracurricular_Activities : <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Internet_Access_at_Home : <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Family_Income_Level : <StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str

In [23]:
required_columns = [
    "Student_ID",
    "Gender",
    "Age",
    "Department",
    "Attendance (%)",
    "Midterm_Score",
    "Final_Score"
]

df[required_columns].isnull().sum()

Student_ID        0
Gender            0
Age               0
Department        0
Attendance (%)    0
Midterm_Score     0
Final_Score       0
dtype: int64

In [24]:
df["Parent_Education_Level"].isnull().sum()

np.int64(1025)

**DATA CLEANING**

In [25]:
cleaned_df = df.copy()

In [26]:
cleaned_df["Parent_Education_Level"] = cleaned_df["Parent_Education_Level"].fillna("Unknown")

In [27]:
cleaned_df["Parent_Education_Level"].isnull().sum()

np.int64(0)

In [28]:
df["Parent_Education_Level"].isnull().sum()

np.int64(1025)

In [29]:
cleaned_df.columns.tolist()

['Student_ID',
 'First_Name',
 'Last_Name',
 'Email',
 'Gender',
 'Age',
 'Department',
 'Attendance (%)',
 'Midterm_Score',
 'Final_Score',
 'Assignments_Avg',
 'Quizzes_Avg',
 'Participation_Score',
 'Projects_Score',
 'Total_Score',
 'Grade',
 'Study_Hours_per_Week',
 'Extracurricular_Activities',
 'Internet_Access_at_Home',
 'Parent_Education_Level',
 'Family_Income_Level',
 'Stress_Level (1-10)',
 'Sleep_Hours_per_Night']

In [30]:
pii_columns = ["First_Name","Last_Name","Email"]
cleaned_df = cleaned_df.drop(columns=pii_columns)

In [35]:
cleaned_df.columns.tolist()

['Student_ID',
 'Gender',
 'Age',
 'Department',
 'Attendance (%)',
 'Midterm_Score',
 'Final_Score',
 'Assignments_Avg',
 'Quizzes_Avg',
 'Participation_Score',
 'Projects_Score',
 'Total_Score',
 'Grade',
 'Study_Hours_per_Week',
 'Extracurricular_Activities',
 'Internet_Access_at_Home',
 'Parent_Education_Level',
 'Family_Income_Level',
 'Stress_Level (1-10)',
 'Sleep_Hours_per_Night']

In [36]:
cleaned_df.shape

(5000, 20)

In [37]:
cleaned_df["Total_Score"].describe()

count    5000.000000
mean       71.652097
std         7.230097
min        50.602000
25%        66.533875
50%        71.696250
75%        76.711625
max        95.091500
Name: Total_Score, dtype: float64

In [38]:
cleaned_df.groupby("Grade")["Total_Score"].agg(["count", "min", "max", "mean"])

       count      min      max       mean
Grade
A         16  90.0900  95.0915  91.277375
B        638  80.0020  89.9665  83.127444
C       2307  70.0005  79.9990  74.515495
D       1760  60.0140  69.9990  65.795618
F        279  50.6020  59.9925  57.552701

In [39]:
cleaned_df.groupby("Grade")["Attendance (%)"].agg(["count", "mean", "min", "max"])

       count       mean    min     max
Grade
A         16  72.855000  50.49   96.94
B        638  74.906129  50.06   99.89
C       2307  75.355856  50.01   99.99
D       1760  75.313375  50.02  100.00
F        279  76.799606  50.02   99.65

In [40]:
assessment_columns = [
    "Midterm_Score",
    "Final_Score",
    "Assignments_Avg",
    "Quizzes_Avg",
    "Participation_Score",
    "Projects_Score"
]

cleaned_df["Average_Assessment_Score"] = cleaned_df[assessment_columns].mean(axis=1)

In [41]:
cleaned_df["Average_Assessment_Score"].describe()

count    5000.000000
mean       69.131297
std         7.516031
min        46.388333
25%        63.794167
50%        69.215833
75%        74.492917
max        94.986667
Name: Average_Assessment_Score, dtype: float64